# Generated by Django 3.2.5 on 2021-07-17 19:08

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(max_length=1000)),
                ('price', models.FloatField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='offerTypeAndValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('offerValue', models.PositiveIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='myOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(validators=[cart.models.inRange])),
                ('offer', models.ManyToManyField(blank=True, to='cart.offerTypeAndValue')),
                ('order_items', models.ManyToManyField(to='cart.itemDetails')),
            ],
        ),
    ]
