# Generated by Django 3.2.5 on 2021-07-17 19:11

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='quantity',
            field=models.PositiveIntegerField(validators=[cart.models.quantityLimit]),
        ),
    ]
