# Generated by Django 3.2.5 on 2021-07-17 19:19

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_itemdetails_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='distance',
            field=models.PositiveIntegerField(validators=[cart.models.inRange]),
        ),
    ]
