# Generated by Django 3.2.5 on 2021-07-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_itemdetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertypeandvalue',
            name='offerValue',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
